### ISSUE TITLE
Prośba o pomoc 

### ISSUE THREAD

**Issue by Krokodyl123** [kamild706/Haxball-Headless-Script#1]
Hej. 

Od jakiegoś czasu piszę skrypt do rooma Fustala i jest on przejmowany przez jakiegoś trola zajmuje wszystkie sloty. Czy mógł byś mi pomóc napisać funkcje tak jak by hasła bezpieczeństwa która wyrzuca wszystkich z rooma a tobie zostawia admina.

Z góry dziękuję.

**Comment by kamild706** [comment]
Github nie jest miejscem na "prośby o pomoc", tylko platformą do dzielenia się kodem open-source, gdzie można zgłaszać błędy czy propozycje rozwoju danego kodu. Czym bardziej, pisanie w moim repozytorium jest nieadekwatne, bo twoja sprawa nawet w najmniejszym calu nie tyczy się mojego skryptu. Jak już musisz to zakładaj takie wątki w oficjalnym repozytorium haxballa.

No ale skoro już zacząłem odpowiadać to przejdźmy do rzeczy. Mamy jeszcze kilka dni wakacji i dzieci siedząc całymi dniami przed komputerem utrudniają grę innym osobom. Wiem coś o tym, bo wyłączyłem swojego rooma z uwagi na ciągle spamujące i zapychające sloty dziecko. Nic się z tym nie da zrobić, bo dzieci poznały dodatki do przeglądarki i jednym kliknięciem zmieniają sobie IP omijając bany i dalej dzielą się z resztą świata swoim smutnym życiem, dopóki mama nie każe im w końcu wyłączyć komputera.
Walka z wiatrakami.

W drodze wyjątku zamieszczam przykładowy kod realizujący zadaną funkcjonalność.
```javascript
room.onPlayerChat = (player, message) => {
  if (message === "haslo") {
    let players = room.getPlayerList().filter(p => p.id !== 0 && p.id !== player.id);
    for (let player of players) {
      room.kickPlayer(player.id, "akysz!");
    }

    room.setPlayerAdmin(player.id, true);
  }
}
```
Pisane z palca, ale powinno działać. Zresztą, jak nie znasz javascriptu to lepiej daj sobie spokój. Próbujesz biegać nie umiejąc chodzić. Szkoda nerwów nie tylko z tego powodu.
