### ISSUE TITLE
Zerowanie statystyk.

### ISSUE THREAD

**Issue by Czoklefr** [kamild706/Haxball-Headless-Script#2]
Jak mam wyzerować statystyki pojedynczemu graczowi?

**Comment by kamild706** [comment]
System statystyk jest tutaj dość nieprzemyślany i nie zaimplementowałem gotowego rozwiązania. Najłatwiej po prostu w konsoli przeglądarki wpisać `goals["nick"] = 0; ownGoals["nick"] = 0; assists["nick"] = 0`.

Dawno tu nie zaglądałem, stąd brak odzewu.
