### ISSUE TITLE
Błąd w kodzie.

### ISSUE THREAD

**Issue by kawfonen** [kamild706/Haxball-Headless-Script#3]
Wykryłem błąd w kodzie mianowicie kiedy byle jaki użytkownik wpisze "!login przykładowy text"

to zalicza go do Super-admina i wtedy nie można zabrać mu adma a w przypadku kicka lub bana ciebie też banuje.  (Oczywiście nie daje adma temu użytkownikowi ale w przypadku gdy ty mu dasz np. to jest to uciążliwe ponieważ dopóki sam nie odda to nic nie możesz zrobić)

PS. Szkoda że nie chcesz mi pomóc z zapisywaniem statystyk oraz zerowniem no ale trudno.

**Comment by kamild706** [comment]
Wiem, że w kodzie jest błąd który po wpisaniu "alogin hasło" dodaje do listy zalogowanych administratorów nawet kiedy logowany użytkownik nie jest uprawniony do zalogowania się. O ile nie jesteś superadminem, to rzeczywiście, próba zbanowania takiego gracza który dostanie uprawnienia admina od innego admina zakończy się banem dla ciebie. Kwestia przeniesienia jednej linijki z 507 do 510 linii.

Ale żeby wpisanie "login hasło" dodawało do grupy superadminów to nie zauważyłem. W tym skrypcie są trzy poziomy admina: super-admin - loguje się globalnym hasłem, admin autoryzowany / zalogowany - loguje się indywidualnym hasłem, oraz zwykły admin nadawany przez innego admina.

Dawno tu nie zaglądałem, stąd też brak odzewu, i nie chce mi się nad tym kodem już pracować - przestałem grać. Ten kod powinien w ogóle być rozplanowany na kilka(naście) plików z sensem... To miał być malutki skrypcik a trochę się rozrósł sam nie wiem kiedy.

Miło mi, że komuś się to przydało. Opublikowałem to tylko po to by trzymać wszystko w jednym miejscu.
