### ISSUE TITLE
Zapisywanie Statystyk.

### ISSUE THREAD

**Issue by Mikimens** [kamild706/Haxball-Headless-Script#4]
Cześć

Korzystam z twego skryptu jest bardzo fajny.

Tylko mam pytanie bo słabo się na tym znam jak zapisać statystyki? Żeby po resecie rooma je przywrócić.

Z góry dziękuję.

**Comment by kamild706** [comment]
Z konsoli należy wywołać `backupServerData();` co spowoduje pobranie pliku ze statystykami. W celu przywrócenia statystyk należy wywołać `restoreServerData();` gdzie jako argument należy podać zawartość pliku ze statystykami otoczoną znakiem backtick , czyli ``restoreServerData(`treść_pliku`);``

**Comment by Fiflaczek324** [comment]
No super działa tylko że jest problem jak gracz ma średnik w nicku masz jakiś sposób?

**Comment by Fiflaczek324** [comment]
To z grawisami zwraca błąd...

**Comment by Fiflaczek324** [comment]
Pomożesz?
